### ISSUE TITLE
validation of arguments

### ISSUE THREAD

**Issue by 0bvim** [willtrigo/42_fract-ol#27]
nivicius in ~/Documents/42_fract-ol on main ● λ ./fractol 1 3
nivicius in ~/Documents/42_fract-ol on main ● λ ./fractol 1 10
nivicius in ~/Documents/42_fract-ol on main ● λ ./fractol 1 9
nivicius in ~/Documents/42_fract-ol on main ● λ ./fractol 1.699 2
nivicius in ~/Documents/42_fract-ol on main ● λ ./fractol juuju
nivicius in ~/Documents/42_fract-ol on main ● λ ./fracto ju
nivicius in ~/Documents/42_fract-ol on main ● λ ./fractol juuju
nivicius in ~/Documents/42_fract-ol on main ● λ ./fractol juuju 1 1
nivicius in ~/Documents/42_fract-ol on main ● λ ./fractol mandelbrown
nivicius in ~/Documents/42_fract-ol on main ● λ ./fractol mandelbrown 1

in all this test program is executed normally!

**Comment by willtrigo** [comment]
ty my friend, now this bug is fixed.
